name: Testing Pipeline

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Pull package data
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup up uv
        run: curl -LsSf https://astral.sh/uv/0.4.5/install.sh | sh

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run code linting
        run: uv run ruff check tenint --exit-zero

      - name: Run unit tests
        run: uv run pytest tests --cov-report term-missing


  security_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Pull package data
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - uses: yezz123/setup-uv@v4
      - uses: snyk/actions/setup@master
      - name: Export a requirements file for Snyk
        run: |
          uv pip compile pyproject.toml -o requirements.txt
          pip3 install -r requirements.txt
      - name: Snyk Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test --command=python3 --skip-unresolved=true
